\connect spotify;

CREATE TABLE artists (
  id INT PRIMARY KEY,
  name TEXT
);

CREATE TABLE albums (
  id INT PRIMARY KEY,
  artist_id INT REFERENCES artists(id),
  name TEXT,
  image TEXT,
  published_year INT
);

CREATE TABLE songs (
  id INT PRIMARY KEY,
  album_id INT REFERENCES albums(id),
  artist_id INT REFERENCES artists(id),
  name TEXT,
  streams INT,
  length INT,
  popularity INT,
  in_library BOOLEAN
);